version: '2.4'

services:
  postgres:
    image: postgres:9.6
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
# Un-comment to access the db service directly
#    ports:
#      - 5432:5432
    networks:
      ${SERVICE_NAME}:
        aliases:
          - datamind
    restart: unless-stopped
    volumes:
      - ${SERVICE_NAME}_data:/var/lib/postgresql/data

  fusionauth:
    image: fusionauth/fusionauth-app:latest
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://datamind:5432/fusionauth
      DATABASE_ROOT_USER: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_MEMORY: ${FUSIONAUTH_MEMORY}
      FUSIONAUTH_SEARCH_ENGINE_TYPE: database
      FUSIONAUTH_URL: http://fusionauth:9011
      FUSIONAUTH_RUNTIME_MODE: development
    networks:
     - ${SERVICE_NAME}
    restart: unless-stopped
    ports:
      - 9011:9011
    volumes:
      - ${SERVICE_NAME}_fa_config:/usr/local/fusionauth/config

networks:
  ${SERVICE_NAME}:
    driver: bridge

volumes:
  ${SERVICE_NAME}_data:
  ${SERVICE_NAME}_fa_config:
